baseurl: "https://yihui.org/"
languageCode: "en-US"
title: "Yihui Xie | 谢益辉"
theme: "hugo-paged"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

outputs:
  home: [html, rss, json]

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "Q&A"
      url: "https://github.com/yihui/yihui.org/discussions"
      weight: 5
    - name: "Todo"
      url: "/todo/"
      weight: 6
    - name: "中文"
      url: "/cn/"
      weight: 7
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "提问"
      url: "https://github.com/yihui/yihui.org/discussions"
      weight: 5
    - name: "菜谱"
      url: "/cn/recipe/"
      weight: 6
    - name: "孩童"
      url: "/cn/kids/"
      weight: 7
    - name: "事务"
      url: "/todo/"
      weight: 8
    - name: "EN"
      url: "/en/"
      weight: 9
  knitr:
    - name: "Home"
      url: "/knitr/"
      weight: 1
    - name: "Options"
      url: "/knitr/options/"
      weight: 2
    - name: "Hooks"
      url: "/knitr/hooks/"
      weight: 3
    - name: "Examples"
      url: "/knitr/demo/"
      weight: 4
    - name: "FAQ"
      url: "/knitr/faq/"
      weight: 5
    - name: "Github"
      pre: "github"
      url: "https://github.com/yihui/knitr"
      weight: 6
    - name: "Yihui Xie"
      url: "/"
      weight: 7
  animation:
    - name: "Home"
      url: "/animation/"
      weight: 1
    - name: "Examples"
      url: "/animation/example/"
      weight: 2
    - name: "Export"
      url: "/animation/export/"
      weight: 3
    - name: "Resources"
      url: "/animation/resources/"
      weight: 4
    - name: "Github"
      pre: "github"
      url: "https://github.com/yihui/animation"
      weight: 5
    - name: "Yihui Xie"
      url: "/"
      weight: 6
  tinytex:
    - name: "Home"
      url: "/tinytex/"
      weight: 1
    - name: "FAQ"
      url: "/tinytex/faq/"
      weight: 2
    - name: "R package"
      url: "/tinytex/r/"
      weight: 3
    - name: "Hall of Pain"
      url: "/tinytex/pain/"
      weight: 4
    - name: "中文文档"
      url: "/tinytex/cn/"
      weight: 5
    - name: "Github"
      pre: "github"
      url: "https://github.com/rstudio/tinytex"
      weight: 6
    - name: "Yihui Xie"
      url: "/"
      weight: 7

params:
  description: "Personal website of Yihui Xie; 谢益辉的个人网站"
  footer: "&copy; [Yihui Xie](/) 2001 - {Year}"
  customJS:
    - "comment-utils.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
  githubContentURL: "https://github.com/yihui/yihui.org/edit/master/content/"
  twitterImage: "/images/logo.png"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Yihui Xie"
    knitr:
      img: "/knitr/images/knit-logo.png"
      url: "/knitr/"
      alt: "knitr logo"
    tinytex:
      img: "/images/logo-tinytex.png"
      url: "/tinytex/"
      alt: "tinytex logo"

  author:
    en: "Yihui Xie"
    cn: "谢益辉"
    animation: "Yihui Xie & Lijia Yu"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"
    search:
      cn: "搜索"
    top:
      cn: "登顶"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
